// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_fXMtMJL4xKe4myrBDQy3clKO63gipK4',
    appId: '1:492509819332:ios:590f6db8c98f4b985b3491',
    messagingSenderId: '492509819332',
    projectId: 'anmates-studio',
    storageBucket: 'anmates-studio.firebasestorage.app',
    iosBundleId: 'com.anmates.anmates',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3nfCpBXiDaoL4g80lJINU2CYKUw8bEfA',
    appId: '1:492509819332:web:557f8670747a5c025b3491',
    messagingSenderId: '492509819332',
    projectId: 'anmates-studio',
    authDomain: 'anmates-studio.firebaseapp.com',
    storageBucket: 'anmates-studio.firebasestorage.app',
    measurementId: 'G-3XVKPDPZZD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTOIYcAegIYKSnf01izV2WDzVVpWOjTco',
    appId: '1:492509819332:android:8ed3f6ed617acc3f5b3491',
    messagingSenderId: '492509819332',
    projectId: 'anmates-studio',
    storageBucket: 'anmates-studio.firebasestorage.app',
  );
}
